language: python
dist: trusty
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- make build
script:
- make check
- make test
env:
  global:
    - secure: ksUzWo3He56TT497XjuCDnj2rIz1pIOYq5tugCwfAlWFVakbajWhcsvnlZ4n4PzgCV6JbseDDZbz4S4uQxujkumjAZ0DOsGeilOhqnyge7D5wFeKsRv2wJTBOLrCeE1GnBXnhZyjDyl69eNNxLzCuDCwrle5gTz/nddWx4waFBM=
    - TX_USR=antoine.abt@camptocamp.com
