version: '3'

volumes:
  hazardsets:

services:

  db:
    image: camptocamp/thinkhazard-testdb

  thinkhazard:
    image: camptocamp/thinkhazard
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment: &env
      - INI_FILE
      - TX_USR
      - TX_PWD
      - PGHOST
      - PGPORT
      - PGUSER_PUBLIC
      - PGPASSWORD_PUBLIC
      - PGDATABASE_PUBLIC
      - PGUSER_ADMIN
      - PGPASSWORD_ADMIN
      - PGDATABASE_ADMIN
      - AWS_ENDPOINT_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
      - GEONODE_URL
      - GEONODE_USERNAME
      - GEONODE_API_KEY
      - ANALYTICS
      - BROKER_URL
      - HTPASSWORDS
    ports:
      - 8080:8080

  taskrunner:
    image: camptocamp/thinkhazard
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment: *env
    command: 'celery -A thinkhazard.celery worker -l info'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: 'minio server /data'

  redis:
    image: redis
    ports:
      - "6379:6379"

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./docker/minio-client/docker-entrypoint:/docker-entrypoint
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
    entrypoint: /docker-entrypoint
    command: ["exit", "0"]
