version: '3'

services:
  thinkhazard:
    image: camptocamp/thinkhazard
    environment:
      - PGHOST
      - PGPORT
      - PGUSER_PUBLIC
      - PGPASSWORD_PUBLIC
      - PGDATABASE_PUBLIC
      - PGUSER_ADMIN
      - PGPASSWORD_ADMIN
      - PGDATABASE_ADMIN
      - INI_FILE
    command: 'pserve c2c://${INI_FILE} -n public'
    ports:
      - 8080:6543
