version: '3'

services:
  thinkhazard:
    image: camptocamp/thinkhazard-builder
    environment:
      USE_CACHE: 'TRUE'
    volumes:
      - '${PWD}/development.ini:/app/development.ini'
      - '${PWD}/thinkhazard:/app/thinkhazard'
    command: 'pserve --reload c2c://development.ini'

  taskrunner:
    image: camptocamp/thinkhazard-builder
    environment:
      USE_CACHE: 'TRUE'
    volumes:
      - '${PWD}/development.ini:/app/development.ini'
      - '${PWD}/thinkhazard:/app/thinkhazard'
