version: '3'

volumes:
  hazardsets:

services:

  db:
    image: camptocamp/thinkhazard-testdb

  thinkhazard:
    image: camptocamp/thinkhazard
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment: &env
      - INI_FILE
      - TX_USR
      - TX_PWD
      - PGHOST
      - PGPORT
      - PGUSER_PUBLIC
      - PGPASSWORD_PUBLIC
      - PGDATABASE_PUBLIC
      - PGUSER_ADMIN
      - PGPASSWORD_ADMIN
      - PGDATABASE_ADMIN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
      - GEONODE_API_KEY
      - ANALYTICS
      - BROKER_URL
    ports:
      - 8080:8080

  taskrunner:
    image: camptocamp/thinkhazard
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment: *env
    command: 'celery -A thinkhazard.celery worker -l info'

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    command: 'server start'

  redis:
    image: redis
    ports:
      - "6379:6379"

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
    entrypoint: >
      /bin/sh -c "
      while ! nc -z minio 9000; do echo 'Wait minio to startup...' && sleep 0.1; done;
      sleep 5;
      /usr/bin/mc config host add localminio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc rm -r --force localminio/${AWS_BUCKET_NAME};
      /usr/bin/mc mb localminio/${AWS_BUCKET_NAME};
      /usr/bin/mc policy download localminio/${AWS_BUCKET_NAME};
      exit 0;
      "
