version: '3'

volumes:
  hazardsets:

services:

  db:
    image: camptocamp/thinkhazard-testdb

  thinkhazard:
    image: camptocamp/thinkhazard
    user: www-data
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - hazardsets:/tmp/hazardsets
    environment:
      - PGHOST
      - PGPORT
      - PGUSER_PUBLIC
      - PGPASSWORD_PUBLIC
      - PGDATABASE_PUBLIC
      - PGUSER_ADMIN
      - PGPASSWORD_ADMIN
      - PGDATABASE_ADMIN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME
      - INI_FILE
      - GEONODE_API_KEY
    command: 'pserve c2c://${INI_FILE}'
    ports:
      - 8080:6543
