version: '3'

services:
  thinkhazard:
    image: camptocamp/thinkhazard
    environment:
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGDATABASE_ADMIN
      - INI_FILE
    command: 'pserve c2c://${INI_FILE} -n public'
    ports:
      - 8080:6543

  thinkhazard_admin:
    image: camptocamp/thinkhazard
    environment:
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGDATABASE_ADMIN
      - INI_FILE
    command: 'pserve c2c://${INI_FILE} -n public'
    ports:
      - 8081:6543


  #thinkhazard_admin:
